### ISSUE TITLE
behavior of `any` on promises that immediately resolve

### ISSUE THREAD

**Issue by szhangpitt** [asfktz/Awaity.js#4]
Hi, Please consider the following code; I passed in promises that "immediately" resolves, I was expecting `any()` would resolve the first one in the array, but it resolves last one. Is it intended behavior?

```js
const { any } = require('awaity/esm');

const fs = [
  async n => n, // resolves 0
  async n => {
    throw new Error(`n!`);
  },            // rejects 1
  async n => n, // resolves 2
];

const ps = fs.map((f, i) => f(i));

any(ps)
  .then(p => console.log(`any resolved:`, p))
  .catch(err => console.error(`any rejected:`, err));

// any resolved: 2

```

**Comment by asfktz** [comment]
Oww good catch, @szhangpitt!

Interesting, no, it should take the first. 

I'll fix it shortly (:
Thanks for the heads up

**Comment by asfktz** [comment]
Hi @szhangpitt, I've released a new version with a fix.

Mind to take a look? (:

**Comment by szhangpitt** [comment]
👍
