### ISSUE TITLE
Does Awaity include Promise polyfill?

### ISSUE THREAD

**Issue by ryantsangai** [asfktz/Awaity.js#8]
I am looking for lightweight Promise library.
This library provide all features I want.

But it seems Promise polyfill is not included?

**Comment by asfktz** [comment]
Hi, @ryantsangai!

> I am looking for lightweight Promise library.
This library provide all features I want.

I glad to hear that 😊


> But it seems Promise polyfill is not included?

You are right, it does not. 


What environment are you planning to support?
Are you using Babel?
If so, you can use [babel-polyfill](https://babeljs.io/docs/usage/polyfill/)

**Comment by ryantsangai** [comment]
Thanks!
Just want to confirm.

I think I will use es-promise polyfill
https://www.npmjs.com/package/es6-promise
